### ISSUE TITLE
Chat input controls have unexpected position when window is smaller

### ISSUE THREAD

**Issue by jonyroda97** [LaserFlash/steam-chat-skin#26]
https://i.imgur.com/DET1Kjo.jpg

Vs

https://i.imgur.com/8PUnTHk.jpg

**Comment by LaserFlash** [comment]
This was an intentional change.
More so for if the window is made even smaller, as it makes sure there is still room for the actual text input.

Changes I could make to improve it:

- style changes to make the wrapped state look better
- go to a wrapped state with a smaller window than current

**Comment by BXZ1** [comment]
> go to a wrapped state with a smaller window than current

this ^

**Comment by LaserFlash** [comment]
cool will probably make that change this evening

**Comment by jonyroda97** [comment]
And an option to enable/disable the send button?
Normally people use Enter right? 😅

**Comment by LaserFlash** [comment]
Your not wrong

I am remembering why I wrapped at that point though. The voice controls if in a call end up there as well. So a lot of buttons

**Comment by LaserFlash** [comment]
Will just have to make it more conditional and try and check if the voice controls are active

**Comment by LaserFlash** [comment]
This is why it was wrapping how it is currently
![image](https://user-images.githubusercontent.com/11022407/68002354-5b31db00-fccd-11e9-9435-7c69c3ca0333.png)

**Comment by LaserFlash** [comment]
This might be the smallest it can go

![image](https://user-images.githubusercontent.com/11022407/68002932-1fe4db80-fcd0-11e9-9926-9dba251ea233.png)
![image](https://user-images.githubusercontent.com/11022407/68002945-30955180-fcd0-11e9-8718-9c38edfa371f.png)
