### ISSUE TITLE
Consider adding font as an option in customization?

### ISSUE THREAD

**Issue by HeavenlyChorus** [LaserFlash/steam-chat-skin#29]
Would be great if the option can let me type in the font name myself.
I'm a Chinese user who needs Microsoft YaHei over the 'idk what it even is' terrible default font.
Thanks in advance.

**Comment by LaserFlash** [comment]
Is this directed at the customisation that can be done through https://steamchatskinning.tk/ or in the friends.custom.css file?

**Comment by HeavenlyChorus** [comment]
> Is this directed at the customisation that can be done through https://steamchatskinning.tk/ or in the friends.custom.css file?

I'm fine with either way, it's up to u. :D

**Comment by LaserFlash** [comment]
@HeavenlyChorus 

Well I will do something with the friends.custom.css soon as that should be straight forward.

Not sure how I would approach the website

**Comment by LaserFlash** [comment]
Made some changes in 088a44fb254ae54b54c3828534dab8ee6b46c6b6

**Comment by LaserFlash** [comment]
@HeavenlyChorus 
You want to add something like the following to friends,custom.css
```css 
* {
   font-family: '宋体',宋体b8b体,Microsoft YaHei, Arial, sans-serif !important;
}
```
I think thats the font-family for Microsoft YaHei but could be wrong

**Comment by LaserFlash** [comment]
Just make sure it is after all the imports

**Comment by HeavenlyChorus** [comment]
> @HeavenlyChorus
> You want to add something like the following to friends,custom.css
> 
> ```css
> * {
>    font-family: '宋体',宋体b8b体,Microsoft YaHei, Arial, sans-serif !important;
> }
> ```
> 
> I think thats the font-family for Microsoft YaHei but could be wrong

Working great, thanks! Not using 宋体 tho, its a serif font.
