### ISSUE TITLE
Offline Skinning of Friends List

### ISSUE THREAD

**Issue by jonyroda97** [LaserFlash/steam-chat-skin#62]
Maybe create the offline skinning of the Friends List

Can be skinned using the `ofriends.custom.css` file

![image](https://user-images.githubusercontent.com/8282833/93026875-140cba00-f601-11ea-9c06-1d01d517706d.png)

**Comment by LaserFlash** [comment]
@jonyroda97

Have a look at https://github.com/LaserFlash/steam-chat-skin/blob/master/ofriends.custom.css

## General Idea
- make use of the file caching steam already does (this should mean the imports work when offline)
- contents goes in Steam/clientui/ofriends.css

At some point I will had the option to download this file from my site (https://steamchatskinning.tk), but for now its manual

**Comment by jonyroda97** [comment]
I create the Pull Request #64 with some small fixes:

- You forgot the `;` after the imports
- Added some comment/uncomment to make it easy to choose the options
- Fixed ofriends file link on README

**Comment by LaserFlash** [comment]
Thanks.

The imports in the fonts section were never meant to be imports just educational links (my bad). So I also updated that
