### ISSUE TITLE
Can you restore the discord icon of "away"? And hide the border of friends? Make all avatars round.

### ISSUE THREAD

**Issue by ZEERDEER** [LaserFlash/steam-chat-skin#66]
![image](https://user-images.githubusercontent.com/10573857/93465562-8f31e100-f91d-11ea-8ebf-0c28d87b84db.png)
![image](https://user-images.githubusercontent.com/10573857/93466241-868dda80-f91e-11ea-882a-1eb1749a10c4.png)
pls pls pls

**Comment by LaserFlash** [comment]
Definitely yes to the discord away icon. I must have accidentally broken it.

As for the avatar shapes my intention is to make a customisation option to remove steams avatar frames, and so always use the avatar shape chosen.

Will probably get both done over the weekend

**Comment by ZEERDEER** [comment]
> Definitely yes to the discord away icon. I must have accidentally broken it.
> 
> As for the avatar shapes my intention is to make a customisation option to remove steams avatar frames, and so always use the avatar shape chosen.
> 
> Will probably get both done over the weekend

Thank you Bryn Bennett <3
You are steam chat skin is best skin ! 👍👍👍👍👍

**Comment by LaserFlash** [comment]
@zeerdeer 

- Away icon should be fixed
- and there is an option to disable avatar frames now (also added to https://steamchatskinning.tk/)

**Comment by ZEERDEER** [comment]
@LaserFlash  Thank you very much!
