### ISSUE TITLE
Own avatar at the top won't adapt with Avatar Frame equipped

### ISSUE THREAD

**Issue by HeavenlyChorus** [LaserFlash/steam-chat-skin#68]
![image](https://user-images.githubusercontent.com/13861429/110174091-8e90f680-7e3a-11eb-8d94-7d9df231dd25.png)
As shown, the circular avatar of my steam friend who equipped an avatar frame, adapts to the box shape.
While my own at the top, doesn't.

**Comment by LaserFlash** [comment]
Will need to get myself an avatar frame first, but will look into it.

**Comment by LaserFlash** [comment]
Should be fixed now
