### ISSUE TITLE
Some Steam update broke the UI

### ISSUE THREAD

**Issue by hyoretsu** [LaserFlash/steam-chat-skin#79]
Already tried generating a new one.
![image](https://user-images.githubusercontent.com/20804322/187093801-d00c89b5-67d6-40d5-96dc-f4a0f4ed592e.png)

**Comment by LaserFlash** [comment]
@hyoretsu are you enrolled in the steam beta?

**Comment by hyoretsu** [comment]
No

**Comment by LaserFlash** [comment]
Hmm, that might be why it broke then.
I had a lot of reports last week of problems and I resolved them, but have just realised I was 9n the steam beta at the time, and they possibly were as well.

Could you join the steam beta and let me know if the issue persists?

**Comment by hyoretsu** [comment]
Didn't fix for me.
![image](https://user-images.githubusercontent.com/20804322/187096050-00eccb14-7ee7-48e9-acdb-904adfaa2226.png)
I'm using:
- Black Theme
- Squircle Avatar
- Discord Styled
- Blur On
- Themed Glow
- Improved Shadows
- Enable

By the way, [I'm not the only one having this](https://github.com/hyoretsu/Ultimate-Steam-Dark-Mode-Skin/issues/3)

**Comment by LaserFlash** [comment]
I shall do a proper look into it this evening (about 8 hours time).

Guess steam may have had some more breaking changes since my last patch

**Comment by LaserFlash** [comment]
Sorry @hyoretsu but I don't seem to be able to reproduce your problem.

---

I've tried with a `friends.custom.css` file like the following
```css
@import url(https://laserflash.tk/steam-chat-skin/src/baseTheme.css);
@import url(https://laserflash.tk/steam-chat-skin/src/css/customisable/colourSet/blackMode.css);
@import url(https://laserflash.tk/steam-chat-skin/src/css/customisable/avatarStyle/squircleAvatar.css);
@import url(https://laserflash.tk/steam-chat-skin/src/css/customisable/avatarStatus/discordStatus.css);
@import url(https://laserflash.tk/steam-chat-skin/src/css/customisable/miniProfile/miniProfileBlur.css);
@import url(https://laserflash.tk/steam-chat-skin/src/css/customisable/statusGlow/themedGlow.css);
@import url(https://laserflash.tk/steam-chat-skin/src/css/customisable/shadowEffects/improvedShadow.css);
```

Which should match your setup.
And I've tried on the steam beta & stable versions.

---

My only suggestion left is try reset steam in the patcher (SFP)

![image](https://user-images.githubusercontent.com/11022407/187151202-2ba06adc-6c57-4176-be0c-8f9f12c158cd.png)

**Comment by deveers** [comment]
Hi @LaserFlash but I've done that and it doesn't make any change

**Comment by hyoretsu** [comment]
I've tried two things, one of the two worked.
