### ISSUE TITLE
avatar frames are larger than avatars (oversized)

### ISSUE THREAD

**Issue by HeavenlyChorus** [LaserFlash/steam-chat-skin#86]
![image](https://github.com/LaserFlash/steam-chat-skin/assets/13861429/6de702af-2af8-41eb-b0dd-4651dd579fff)

as screenshot shows, the avatars are only taking top left part of the frames, currently

**Comment by LaserFlash** [comment]
What config/options are you using?

I tried with
```css
@import url(https://ccss.lasr.dev/friends-client/friends-client.css);
@import url(https://ccss.lasr.dev/friends-client/colourSet/discordColours.css);
@import url(https://ccss.lasr.dev/friends-client/avatarStyle/squareAvatar.css);
@import url(https://ccss.lasr.dev/friends-client/avatarStatus/discordStatus.css);
@import url(https://ccss.lasr.dev/friends-client/miniProfile/miniProfileBlur.css);
@import url(https://ccss.lasr.dev/friends-client/statusGlow/themedGlow.css);
@import url(https://ccss.lasr.dev/friends-client/shadowEffects/improvedShadow.css);
```

And that looks fine
![image](https://github.com/LaserFlash/steam-chat-skin/assets/11022407/c50be27a-afdb-410e-b62b-cf4b48d33eb5)

---

Its also possible that you have an old library skin conflicting and overriding the size of avatars.

**Comment by HeavenlyChorus** [comment]
> What config/options are you using?
> 
> I tried with
> 
> ```css
> @import url(https://ccss.lasr.dev/friends-client/friends-client.css);
> @import url(https://ccss.lasr.dev/friends-client/colourSet/discordColours.css);
> @import url(https://ccss.lasr.dev/friends-client/avatarStyle/squareAvatar.css);
> @import url(https://ccss.lasr.dev/friends-client/avatarStatus/discordStatus.css);
> @import url(https://ccss.lasr.dev/friends-client/miniProfile/miniProfileBlur.css);
> @import url(https://ccss.lasr.dev/friends-client/statusGlow/themedGlow.css);
> @import url(https://ccss.lasr.dev/friends-client/shadowEffects/improvedShadow.css);
> ```
> 
> And that looks fine ![image](https://user-images.githubusercontent.com/11022407/246582518-c50be27a-afdb-410e-b62b-cf4b48d33eb5.png)
> 
> Its also possible that you have an old library skin conflicting and overriding the size of avatars.

```css
@import url(https://ccss.lasr.dev/friends-client/friends-client.css);
@import url(https://ccss.lasr.dev/friends-client/colourSet/steamColours.css);
@import url(https://ccss.lasr.dev/friends-client/avatarStyle/roundAvatar.css);
@import url(https://ccss.lasr.dev/friends-client/avatarStatus/discordStatus.css);
@import url(https://ccss.lasr.dev/friends-client/miniProfile/miniProfileBlur.css);
@import url(https://ccss.lasr.dev/friends-client/statusGlow/themedGlow.css);
@import url(https://ccss.lasr.dev/friends-client/shadowEffects/improvedShadow.css);
@import url();
```

**Comment by HeavenlyChorus** [comment]
![image](https://github.com/LaserFlash/steam-chat-skin/assets/13861429/c1d02ff8-1ca8-45e0-8d8f-9dd0f9414499)

im using Fluent by https://github.com/AikoMidori/SteamSkins and its still like this rn

**Comment by HeavenlyChorus** [comment]
weird that even i chose circle avatars in your skin, some are displayed square (the ones with avatar frames)

**Comment by LaserFlash** [comment]
> weird that even i chose circle avatars in your skin, some are displayed square (the ones with avatar frames)

Yeah I have it so avatars with a frame always end up square, they look pretty stupid otherwise.

There is an option to hide frames and have the avatar round though.

**Comment by LaserFlash** [comment]
> ![image](https://github.com/LaserFlash/steam-chat-skin/assets/13861429/c1d02ff8-1ca8-45e0-8d8f-9dd0f9414499)
> 
> im using Fluent by https://github.com/AikoMidori/SteamSkins and its still like this rn

Hmm, I don't think that should conflict, not with the new patching process.

Were you on the steam beta before they rolled out the client changes?

If not and you only just updated to the new SFP did you reset everything before upgrading (as required)?

https://github.com/PhantomGamers/SFP/releases/tag/0.0.45-alpha

If not any library skin you used to use could still be being applied, and causing problems.

**Comment by HeavenlyChorus** [comment]
> > ![image](https://user-images.githubusercontent.com/13861429/246601162-c1d02ff8-1ca8-45e0-8d8f-9dd0f9414499.png)
> > im using Fluent by https://github.com/AikoMidori/SteamSkins and its still like this rn
> 
> Hmm, I don't think that should conflict, not with the new patching process.
> 
> Were you on the steam beta before they rolled out the client changes?
> 
> If not and you only just updated to the new SFP did you reset everything before upgrading (as required)?
> 
> https://github.com/PhantomGamers/SFP/releases/tag/0.0.45-alpha
> 
> If not any library skin you used to use could still be being applied, and causing problems.

oh that's it! i didnt reset, did just now and its all good, thanks
